name: Push to Public Deploy Repo

on:
  push:
    branches:
      - develop

jobs:
  push-to-public:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: fiuba-pylab/pylab
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to public repo
        run: |
          git remote add public https://fiuba-pylab:${{ secrets.PUSH_TOKEN }}@github.com/fiuba-pylab/pylab-deploy.git
          git push public main